Load more and scrolling in categories has duplicates.
offset was overflowing the max u8 when clicking "load more" in categorises and would give the following message

thread 'tokio-runtime-worker' panicked at src/sql.rs:625:18:
attempt to multiply with overflow

The same has been done in multiple places in this file already for offset I'm assuming this one was just missed.